### ISSUE TITLE
wrong link on website

### ISSUE THREAD

**Issue by galantra** [dracula/keypirinha#1]
Hi there. Thanks for your theme! I use it with a couple of apps and I'm adding more. 

I want you to know that the link on your page https://draculatheme.com/keypirinha leads to https://github.com/dracula/keypirinha.git/master.zip, which is the wrong URL

**Comment by mawiseman** [comment]
Thanks for sharing @galantra 
I fixed it now, hopefully wont take long to update the main site

In case you couldn't find it the download is here:
https://github.com/dracula/keypirinha/archive/master.zip
